### ISSUE TITLE
Request to contribute

### ISSUE THREAD

**Issue by princekelly1** [konstantint/steem-stats#1]
Hi
I wish you can add a license to the project and make it more open source , so people can either fork for contributions and also i would be glad to add the following documents to the project which can be integrated to the projects website.
* Readme 
* Terms of service
* Privacy policy
* disclaimer 
* FAQ

**Comment by konstantint** [comment]
I'm not exactly sure what you mean by "the projects website" nor what should one write in the files like "privacy policy", "disclaimer", "terms of service" or "FAQ". It seems those notions don't really apply to this repository.

You are right about the license, though. I'll add one now.

**Comment by princekelly1** [comment]
OK thanks
